jobs:
  build_a5:
    machine: true
    image: ubuntu-2004:current
    working_directory: ~/halium
    environment:
      DEVICE: a5y17lte
      ANDROID_ROOT: ~/halium
    steps:
      - checkout
      - run:
          name: Initialization environment
          command: |
            sudo apt update
            sudo apt-get install -y \
            git gnupg flex ccache bison gperf build-essential \
            zip bzr curl libc6-dev x11proto-core-dev \
            libgl1-mesa-dev g++-multilib tofrodos \
            python3-markdown libxml2-utils xsltproc schedtool \
            liblz4-tool bc lzop imagemagick libncurses5 rsync \
            python-is-python3
            
      - run:
          name: Download repo
          command: |
            mkdir -p ~/bin
            wget 'https://storage.googleapis.com/git-repo-downloads/repo' -P ~/bin
            chmod +x ~/bin/repo
            git config --global user.name "aymanrgab"
            git config --global user.email "aymanrar2c@gmail.com"
            
      - run:
          name: Downloading source code
          command: |
            source hadk.env
            mkdir -p $ANDROID_ROOT
            cd $ANDROID_ROOT
            repo init -u https://github.com/Halium/android.git -b halium-10.0 --depth=1
            repo sync
            git clone -b lineage-17.1_7880only https://github.com/aymanrgab/proprietary_vendor_samsung.git vendor/samsung --depth 1

      - run:
          name: Build Recovery
          command: |
            chmod +x build.sh
            bash build.sh
            tar -czf ~/a5y17lte.tar.gz ~/halium/out/target/product/a5y17lte/recovery.img
      - run:
          name: Check free disk
          when: on_fail
          command: |
            df -h

      - store_artifacts:
          path: ~/a5y17lte.tar.gz

  build_a7:
    machine: true
    image: ubuntu-2004:current
    working_directory: ~/halium
    environment:
      DEVICE: a7y17lte
      ANDROID_ROOT: ~/halium
    steps:
      - checkout
      - run:
          name: Initialization environment
          command: |
            sudo apt update
            sudo apt-get install -y \
            git gnupg flex ccache bison gperf build-essential \
            zip bzr curl libc6-dev x11proto-core-dev \
            libgl1-mesa-dev g++-multilib tofrodos \
            python3-markdown libxml2-utils xsltproc schedtool \
            liblz4-tool bc lzop imagemagick libncurses5 rsync \
            python-is-python3
            
      - run:
          name: Download repo
          command: |
            mkdir -p ~/bin
            wget 'https://storage.googleapis.com/git-repo-downloads/repo' -P ~/bin
            chmod +x ~/bin/repo
            git config --global user.name "aymanrgab"
            git config --global user.email "aymanrar2c@gmail.com"
            
      - run:
          name: Downloading source code
          command: |
            source hadk_a7.env
            mkdir -p $ANDROID_ROOT
            cd $ANDROID_ROOT
            repo init -u https://github.com/Halium/android.git -b halium-10.0 --depth=1
            repo sync
            git clone -b lineage-17.1_7880only https://github.com/aymanrgab/proprietary_vendor_samsung.git vendor/samsung --depth 1

      - run:
          name: Build Recovery
          command: |
            chmod +x build_a7.sh
            bash build_a7.sh
            tar -czf ~/a7y17lte.tar.gz ~/halium/out/target/product/a7y17lte/recovery.img
      - run:
          name: Check free disk
          when: on_fail
          command: |
            df -h

      - store_artifacts:
          path: ~/a7y17lte.tar.gz
          
workflows:
  version: 2
  build_and_upload:
    jobs:
      - build_a5
      - build_a7
