
name: Build RecoveryRamDisk

on: 
  release:
    types: [published]
  push:
    branches: 
      - master

jobs:

  build:
    runs-on: ubuntu-20.04

    env:
      DEVICE: a5y17lte
      ANDROID_ROOT: /home/runner/work/halium/

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Initialization environment
      run: |
        sudo dpkg --add-architecture i386
        sudo apt update
        sudo apt-get install -y \
        git gnupg flex bison gperf build-essential \
        zip bzr curl libc6-dev libncurses5-dev:i386 x11proto-core-dev \
        libx11-dev:i386 libreadline6-dev:i386 libgl1-mesa-glx:i386 \
        libgl1-mesa-dev g++-multilib mingw-w64-i686-dev tofrodos \
        python3-markdown libxml2-utils xsltproc zlib1g-dev:i386 schedtool \
        liblz4-tool bc lzop imagemagick libncurses5 rsync \
        python-is-python3

    - name: Download repo
      run: |
        mkdir -p ~/bin
        wget 'https://storage.googleapis.com/git-repo-downloads/repo' -P ~/bin
        chmod +x ~/bin/repo
        git config --global user.name "aymanrgab"
        git config --global user.email "aymanrar2c@gmail.com"

    - name: Downloading source code
      run: |
        source hadk.env
        mkdir -p $ANDROID_ROOT
        cd $ANDROID_ROOT
        repo init -u https://github.com/muhammad23012009/halium_recovery_minimal.git --depth=1
        git clone -b halium https://github.com/Exynos7880-Linux/local_manifests.git .repo/local_manifests
        repo sync
        
    - name: Build Recovery
      run: |
        chmod +x build.sh
        bash build.sh
      shell: bash

    - name: Check free disk
      if: failure()
      run: |
        df -h
      shell: bash

    - name : Upload ramdisk image
      uses: actions/upload-artifact@main
      with:
        name: recoveryramdisk
        path: ${{env.ANDROID_ROOT}}/out/target/product/${{env.DEVICE}}/*.img

